export const Channels = {
  ProjectsList: 'projects:list',
  ProjectsGet: 'projects:get',
  ProjectsCreate: 'projects:create',
  ProjectsUpdate: 'projects:update',
  ProjectsDelete: 'projects:delete',
  TasksList: 'tasks:list',
  TasksGet: 'tasks:get',
  TasksCreate: 'tasks:create',
  TasksUpdate: 'tasks:update',
  TasksArchive: 'tasks:archive',
  TasksFocus: 'tasks:focus',
  ColumnHistoryCreate: 'columnHistory:create',
  LinksList: 'links:list',
  LinksCreate: 'links:create',
  LinksDelete: 'links:delete',
  DialogOpenImage: 'dialog:open-image',
  ColorsExtractPalette: 'colors:extract-palette',
  FilesCopyToAppData: 'files:copy-to-app-data',
  IntakeFetchMetadata: 'intake:fetchMetadata',
  IntakeProcessTask: 'intake:processTask',
  DebugSubscribe: 'debug:subscribe',
  DebugUnsubscribe: 'debug:unsubscribe',
  LlmValidateModel: 'llm:validateModel'
} as const
